config/routes.rb
Rails.application.routes.draw do
  resources :posts do
   resources :comments
  end
  resources :jankens

  resources :games
  resources :uranais
  resources :users
  resources :books

root 'welcome#index'
get 'welcome/member'

end

app/models/uranai.rb
class Uranai < ActiveRecord::Base
end

app/controllers/uranais_controller.rb
class UranaisController < ApplicationController
  before_action :set_uranai, only: [:show, :edit, :update, :destroy]

  # GET /uranais
  # GET /uranais.json
  def index
    @uranais = Uranai.all
  end

  # GET /uranais/1
  # GET /uranais/1.json
  def show
  end

  # GET /uranais/new
  def new
    @uranai = Uranai.new
  end

  # GET /uranais/1/edit
  def edit
  end

  # POST /uranais
  # POST /uranais.json
  def create
    @uranai = Uranai.new(uranai_params)

    respond_to do |format|
      if @uranai.save
        format.html { redirect_to @uranai, notice: 'Uranai was successfully created.' }
        format.json { render :show, status: :created, location: @uranai }
      else
        format.html { render :new }
        format.json { render json: @uranai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uranais/1
  # PATCH/PUT /uranais/1.json
  def update
    respond_to do |format|
      if @uranai.update(uranai_params)
        format.html { redirect_to @uranai, notice: 'Uranai was successfully updated.' }
        format.json { render :show, status: :ok, location: @uranai }
      else
        format.html { render :edit }
        format.json { render json: @uranai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uranais/1
  # DELETE /uranais/1.json
  def destroy
    @uranai.destroy
    respond_to do |format|
      format.html { redirect_to uranais_url, notice: 'Uranai was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uranai
      @uranai = Uranai.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uranai_params
      params.require(:uranai).permit(:luck, :detail)
    end
end

app/helpers/uranais_helper.rb
module UranaisHelper
end

app/views/uranais/_form.html.erb
<%= form_for(@uranai) do |f| %>
  <% if @uranai.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uranai.errors.count, "error") %> prohibited this uranai from being saved:</h2>

      <ul>
      <% @uranai.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :luck %><br>
    <%= f.text_field :luck %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uranais/edit.html.erb
<h1>Editing Uranai</h1>

<%= render 'form' %>

<%= link_to 'Show', @uranai %> |
<%= link_to 'Back', uranais_path %>

app/views/uranais/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Uranais</h1>

<table>
  <thead>
    <tr>
      <th>Luck</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uranais.each do |uranai| %>
      <tr>
        <td><%= uranai.luck %></td>
        <td><%= uranai.detail %></td>
        <td><%= link_to 'Show', uranai %></td>
        <td><%= link_to 'Edit', edit_uranai_path(uranai) %></td>
        <td><%= link_to 'Destroy', uranai, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uranai', new_uranai_path %>

app/views/uranais/new.html.erb
<h1>New Uranai</h1>

<%= render 'form' %>

<%= link_to 'Back', uranais_path %>

app/views/uranais/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Luck:</strong>
  <%= @uranai.luck %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @uranai.detail %>
</p>

<%= link_to 'Edit', edit_uranai_path(@uranai) %> |
<%= link_to 'Back', uranais_path %>